- name: AWS VPC
  hosts: localhost
  gather_facts: false
  tags: [vpc]
  tasks:
    - name: Load Configs
      vars:
        load_config_type: vpc
        load_config_var: desired_vpcs
      ansible.builtin.include_tasks: tasks/copy_configs.yml

    - name: Create a VPC
      amazon.aws.ec2_vpc_net:
        name: '{{ _vpc.name }}'
        cidr_block: '{{ _vpc.cidr_block }}'
        region: '{{ _vpc.region }}'
        state: present
      loop: '{{ desired_vpcs.values() | list | flatten }}'
      loop_control:
        loop_var: _vpc

- name: AWS VPC Internet Gateways
  hosts: localhost
  gather_facts: false
  tags: [vpc, vpc-internet-gateways]
  tasks:
    - name: Load Configs
      vars:
        load_config_type: vpc-internet-gateways
        load_config_var: desired_vpc_igws
      ansible.builtin.include_tasks: tasks/copy_configs.yml

    - name: Create VPC Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: '{{ _vpc_igw.vpc_name | get_aws_resource_id("vpc", _vpc_igw.region) }}'
        region: '{{ _vpc_igw.region }}'
        tags: '{{ _vpc_igw.tags }}'
        state: present
      loop: '{{ desired_vpc_igws.values() | list | flatten }}'
      loop_control:
        loop_var: _vpc_igw

- name: AWS VPC Subnets
  hosts: localhost
  gather_facts: false
  tags: [vpc, vpc-subnets]
  tasks:
    - name: Load Configs
      vars:
        load_config_type: vpc-subnets
        load_config_var: desired_vpc_subnets
      ansible.builtin.include_tasks: tasks/copy_configs.yml

    - name: Create a VPC Subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ _vpc_subnet.vpc_name | get_aws_resource_id('vpc', _vpc_subnet.region) }}"
        region: "{{ _vpc_subnet.region }}"
        cidr: "{{ _vpc_subnet.cidr }}"
        az: "{{ _vpc_subnet.az }}"
        tags: "{{ _vpc_subnet.tags }}"
        state: present
      loop: '{{ desired_vpc_subnets.values() | list | flatten }}'
      loop_control:
        loop_var: _vpc_subnet

- name: AWS VPC NAT Gateways
  hosts: localhost
  gather_facts: false
  tags: [vpc, vpc-nat-gateways]
  tasks:
    - name: Load Configs
      vars:
        load_config_type: vpc-nat-gateways
        load_config_var: desired_vpc_nat_gateways
      ansible.builtin.include_tasks: tasks/copy_configs.yml

    - name: Create a VPC NAT Gateways
      amazon.aws.ec2_vpc_nat_gateway:
        subnet_id: "{{ _vpc_nat_gateway.subnet_name | get_aws_resource_id('subnet', _vpc_nat_gateway.region) }}"
        if_exist_do_not_create: true
        region: "{{ _vpc_nat_gateway.region }}"
        state: present
      loop: '{{ desired_vpc_nat_gateways.values() | list | flatten }}'
      loop_control:
        loop_var: _vpc_nat_gateway

  # Route tables with internet gateway routes require internet gateways to exist first
- name: AWS VPC Route Tables
  hosts: localhost
  gather_facts: false
  tags: [vpc, vpc-route-tables]
  tasks:
    - name: Load Configs
      vars:
        load_config_type: vpc-route-tables
        load_config_var: desired_vpc_route_tables
      ansible.builtin.include_tasks: tasks/copy_configs.yml

    - name: Create VPC Route Tables
      amazon.aws.ec2_vpc_route_table:
        vpc_id: '{{ _vpc_route_table.vpc_name | get_aws_resource_id("vpc", _vpc_route_table.region) }}'
        region: '{{ _vpc_route_table.region }}'
        tags: '{{ _vpc_route_table.tags }}'
        subnets: >-
          {{ _vpc_route_table.subnets | get_aws_resource_ids("subnet", _vpc_route_table.region) }}
        routes: >-
          {{ _vpc_route_table.routes | resolve_route_gateway_ids(_vpc_route_table.region) }}
        state: present
      loop: '{{ desired_vpc_route_tables.values() | list | flatten }}'
      loop_control:
        loop_var: _vpc_route_table

- name: AWS VPC Network ACLs
  hosts: localhost
  gather_facts: false
  tags: [vpc, vpc-network-acls]
  tasks:
    - name: Load Configs
      vars:
        load_config_type: vpc-network-acls
        load_config_var: desired_vpc_nacls
      ansible.builtin.include_tasks: tasks/copy_configs.yml

    - name: Create VPC Network ACLs
      community.aws.ec2_vpc_nacl:
        vpc_id: '{{ _vpc_nacl.vpc_name | get_aws_resource_id("vpc", _vpc_nacl.region) }}'
        region: '{{ _vpc_nacl.region }}'
        name: '{{ _vpc_nacl.name }}'
        subnets: >-
          {{ _vpc_nacl.subnets | get_aws_resource_ids("subnet", _vpc_nacl.region) }}
        ingress: '{{ _vpc_nacl.ingress | default([]) }}'
        egress: '{{ _vpc_nacl.egress | default([]) }}'
        state: present
      loop: '{{ desired_vpc_nacls.values() | list | flatten }}'
      loop_control:
        loop_var: _vpc_nacl

- name: AWS VPC Security Groups
  hosts: localhost
  gather_facts: false
  tags: [vpc, vpc-security-groups]
  tasks:
    - name: Load Configs
      vars:
        load_config_type: vpc-security-groups
        load_config_var: desired_vpc_security_groups
      ansible.builtin.include_tasks: tasks/copy_configs.yml

    - name: Create VPC Security Groups
      amazon.aws.ec2_security_group:
        vpc_id: '{{ _vpc_sg.vpc_name | get_aws_resource_id("vpc", _vpc_sg.region) }}'
        region: '{{ _vpc_sg.region }}'
        name: '{{ _vpc_sg.name }}'
        description: '{{ _vpc_sg.description }}'
        rules: '{{ _vpc_sg.rules | default([]) }}'
        rules_egress: '{{ _vpc_sg.rules_egress | default([]) }}'
        tags: '{{ _vpc_sg.tags }}'
        state: present
      loop: '{{ desired_vpc_security_groups.values() | list | flatten }}'
      loop_control:
        loop_var: _vpc_sg

- name: AWS VPC Endpoints
  hosts: localhost
  gather_facts: false
  tags: [vpc, vpc-endpoints]
  tasks:
    - name: Load Configs
      vars:
        load_config_type: vpc-endpoints
        load_config_var: desired_vpc_endpoints
      ansible.builtin.include_tasks: tasks/copy_configs.yml

    - name: Create VPC Gateway Endpoints
      amazon.aws.ec2_vpc_endpoint:
        vpc_id: '{{ _vpc_endpoint.vpc_name | get_aws_resource_id("vpc", _vpc_endpoint.region) }}'
        region: '{{ _vpc_endpoint.region }}'
        service: 'com.amazonaws.{{ _vpc_endpoint.region }}.{{ _vpc_endpoint.service }}'
        vpc_endpoint_type: Gateway
        route_table_ids: >-
          {{ _vpc_endpoint.route_table_names | get_aws_resource_ids("route_table", _vpc_endpoint.region) }}
        tags: '{{ _vpc_endpoint.tags }}'
        state: present
      loop: '{{ desired_vpc_endpoints.values() | list | flatten }}'
      loop_control:
        loop_var: _vpc_endpoint
      when: _vpc_endpoint.endpoint_type == 'Gateway'

    - name: Create VPC Interface Endpoints
      amazon.aws.ec2_vpc_endpoint:
        vpc_id: '{{ _vpc_endpoint.vpc_name | get_aws_resource_id("vpc", _vpc_endpoint.region) }}'
        region: '{{ _vpc_endpoint.region }}'
        service: 'com.amazonaws.{{ _vpc_endpoint.region }}.{{ _vpc_endpoint.service }}'
        vpc_endpoint_type: Interface
        vpc_endpoint_subnets: >-
          {{ _vpc_endpoint.subnet_names | get_aws_resource_ids("subnet", _vpc_endpoint.region) }}
        vpc_endpoint_security_groups: >-
          {{ _vpc_endpoint.security_group_names | get_aws_resource_ids("security_group", _vpc_endpoint.region) }}
        tags: '{{ _vpc_endpoint.tags }}'
        state: present
      loop: '{{ desired_vpc_endpoints.values() | list | flatten }}'
      loop_control:
        loop_var: _vpc_endpoint
      when: _vpc_endpoint.endpoint_type == 'Interface'
