- name: AWS IAM Users
  hosts: localhost
  gather_facts: false
  tags: [iam, iam-users]
  tasks:
    - name: Load Configs
      vars:
        load_config_type: iam-users
        load_config_var: desired_iam_users
      ansible.builtin.include_tasks: tasks/copy_configs.yml

    - name: Create a user in IAM
      amazon.aws.iam_user:
        name: '{{ _iam_user.name }}'
        managed_policies: '{{ _iam_user.managed_policies | default([]) }}'
        state: present
      loop: '{{ desired_iam_users.values() | list | flatten }}'
      loop_control:
        loop_var: _iam_user

- name: AWS IAM Roles
  hosts: localhost
  gather_facts: false
  tags: [iam, iam-roles]
  tasks:
    - name: Load Configs
      vars:
        load_config_type: iam-roles
        load_config_var: desired_iam_roles
      ansible.builtin.include_tasks: tasks/copy_configs.yml

    - name: Create a role in IAM
      amazon.aws.iam_role:
        name: '{{ _iam_roles.name }}'
        assume_role_policy_document: '{{ _iam_roles.assume_role_policy_document | to_json }}'
        managed_policies: '{{ _iam_roles.managed_policies | default([]) }}'
        state: present
      loop: '{{ desired_iam_roles.values() | list | flatten }}'
      loop_control:
        loop_var: _iam_roles

- name: AWS IAM Instance Profiles
  hosts: localhost
  gather_facts: false
  tags: [iam, iam-instance-profiles]
  tasks:
    - name: Load Configs
      vars:
        load_config_type: iam-instance-profiles
        load_config_var: desired_iam_instance_profiles
      ansible.builtin.include_tasks: tasks/copy_configs.yml

    - name: Create IAM Instance Profiles
      amazon.aws.iam_instance_profile:
        name: '{{ _instance_profile.name }}'
        role: '{{ _instance_profile.role }}'
        state: present
      loop: '{{ desired_iam_instance_profiles.instance_profiles_list }}'
      loop_control:
        loop_var: _instance_profile
